### ISSUE TITLE
Unexpected ACK-only packet sent

### ISSUE THREAD

**Issue by Archieeeeee** [quinn-rs/quinn#1196]
I can't reproduce this error but it happens sometimes, what may cause this error so？
btw, I'm writing an proxy app using quinn,  this error happens for me sometimes when I drag youtube video progress bar

```text

thread 'tokio-runtime-worker' panicked at 'SendableFrames was SendableFrames { acks: false, other: true }, but only ACKs have been written', /root/.cargo/git/checkouts/quinn-b26c2db1d34f0cc5/8c27e64/quinn-proto/src/connection/mod.rs:740:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/git/checkouts/quinn-b26c2db1d34f0cc5/8c27e64/quinn/src/mutex.rs:138:42
stack backtrace:
   0:     0x55d39b92a200 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d39b92a200 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d39b92a200 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d39b92a200 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d39b945b5c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55d39b924b55 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55d39b92c16b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d39b92c16b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d39b92c16b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55d39b92bc41 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55d39b92c834 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x55d39b92c317 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x55d39b92a6fc - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d39b92c279 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x55d39b40de71 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x55d39b40df03 - core::result::unwrap_failed::h2d8d0952e3250de9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:     0x55d39b414ba2 - core::result::Result<T,E>::unwrap::h863bdbb253b52bb3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1281:23
  17:     0x55d39b4746c4 - quinn::mutex::non_tracking::Mutex<T>::lock::h351241cc7024e719
                               at /root/.cargo/git/checkouts/quinn-b26c2db1d34f0cc5/8c27e64/quinn/src/mutex.rs:138:24
  18:     0x55d39b446579 - <quinn::connection::ConnectionRef<S> as core::ops::drop::Drop>::drop::h7751ba6e6801e6f7
                               at /root/.cargo/git/checkouts/quinn-b26c2db1d34f0cc5/8c27e64/quinn/src/connection.rs:748:26
  19:     0x55d39b43ce73 - core::ptr::drop_in_place<quinn::connection::ConnectionRef<quinn_proto::crypto::rustls::TlsSession>>::h1bdee32a9d0e950e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  20:     0x55d39b43d4fa - core::ptr::drop_in_place<quinn::connection::ConnectionDriver<quinn_proto::crypto::rustls::TlsSession>>::h3fb6f7df7746720a
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  21:     0x55d39b43ecfb - core::ptr::drop_in_place<tokio::runtime::task::core::Stage<quinn::connection::ConnectionDriver<quinn_proto::crypto::rustls::TlsSession>>>::hd143ba36818f1630
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  22:     0x55d39b4d1cbf - tokio::runtime::task::core::CoreStage<T>::set_stage::{{closure}}::h1c1f134192175828
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:214:35
  23:     0x55d39b4fcdbc - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h0dccc33da9e69f8b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  24:     0x55d39b4d1b03 - tokio::runtime::task::core::CoreStage<T>::set_stage::h194fd9bd18b16eb6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:214:9
  25:     0x55d39b4d0709 - tokio::runtime::task::core::CoreStage<T>::drop_future_or_output::h48da35986750bc78
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:180:13
  26:     0x55d39b43b3ad - <tokio::runtime::task::harness::poll_future::{{closure}}::Guard<T> as core::ops::drop::Drop>::drop::h24447d1f3c7f66ae
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:457:17
  27:     0x55d39b43f5ba - core::ptr::drop_in_place<tokio::runtime::task::harness::poll_future::{{closure}}::Guard<quinn::connection::ConnectionDriver<quinn_proto::crypto::rustls::TlsSession>>>::ha6f765fb9ce6c17e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ptr/mod.rs:192:1
  28:     0x55d39b4d7e02 - tokio::runtime::task::harness::poll_future::{{closure}}::h54be8e584e432568
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:464:5
  29:     0x55d39b514e63 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7805e1bd1e4fec2d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:347:9
  30:     0x55d39b44d0e0 - std::panicking::try::do_call::hd74f1ffaa2ac36b1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  31:     0x55d39b44ff6d - __rust_try
  32:     0x55d39b44877a - std::panicking::try::h1ba2ee6550e063a9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  33:     0x55d39b515dba - std::panic::catch_unwind::h81f3fceb9f8b2f71
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  34:     0x55d39b4d776b - tokio::runtime::task::harness::poll_future::hd71bef73d53f05e1
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  35:     0x55d39b4da319 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hf547f63fdf6cec92
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  36:     0x55d39b4e25f3 - tokio::runtime::task::harness::Harness<T,S>::poll::h02cac3f34bcb9e77
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  37:     0x55d39b46e530 - tokio::runtime::task::raw::poll::h72f5189f5f51bfd8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  38:     0x55d39b5d1e2f - tokio::runtime::task::raw::RawTask::poll::h1529a45f52063cc2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  39:     0x55d39b59a962 - tokio::runtime::task::LocalNotified<S>::run::hfacae628f00c82de
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:343:9
  40:     0x55d39b5e286d - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::hd1286b411e849b42
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:443:21
  41:     0x55d39b5b3e1c - tokio::coop::with_budget::{{closure}}::h3d700afc77607352
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  42:     0x55d39b5ea7e4 - std::thread::local::LocalKey<T>::try_with::hcc45646a37b340a0
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:399:16
  43:     0x55d39b5e906e - std::thread::local::LocalKey<T>::with::hdf721bedc67da410
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/local.rs:375:9
  44:     0x55d39b5e235c - tokio::coop::with_budget::h04617dc54dcbba4a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  45:     0x55d39b5e235c - tokio::coop::budget::hf191955dc73728e9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  46:     0x55d39b5e235c - tokio::runtime::thread_pool::worker::Context::run_task::hf7941b2952ddcf8d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:419:9
  47:     0x55d39b5e1bf2 - tokio::runtime::thread_pool::worker::Context::run::hd7f9a0531c5607cd
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:386:24
  48:     0x55d39b5e19e3 - tokio::runtime::thread_pool::worker::run::{{closure}}::h58c361df7b12a197
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:371:17
  49:     0x55d39b61060d - tokio::macros::scoped_tls::ScopedKey<T>::set::hc05e3539267213a9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  50:     0x55d39b5e190c - tokio::runtime::thread_pool::worker::run::h4f6f0f9fa20bb909
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:368:5
  51:     0x55d39b5e177b - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::he87f71da011d9c61
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:347:45
  52:     0x55d39b5a567f - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hbd0b42decee12d0d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/task.rs:42:21
  53:     0x55d39b5b654e - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hb6a0a4e678cfd79a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  54:     0x55d39b5f7f05 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he1d2387c9c8f07db
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  55:     0x55d39b5b63f8 - tokio::runtime::task::core::CoreStage<T>::poll::hcd703140c1465f36
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  56:     0x55d39b5da64e - tokio::runtime::task::harness::poll_future::{{closure}}::hfa471b1b60d61fd9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  57:     0x55d39b59ce83 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9c08714735611d59
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:347:9
  58:     0x55d39b5aca92 - std::panicking::try::do_call::he6a9c8018fe04fa0
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  59:     0x55d39b5acf1d - __rust_try
  60:     0x55d39b5ac86a - std::panicking::try::he6739a0c954a7a0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  61:     0x55d39b59eadb - std::panic::catch_unwind::h2bf0d0f4dc3b2957
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  62:     0x55d39b5da4cc - tokio::runtime::task::harness::poll_future::hf5f51847f70dee0e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  63:     0x55d39b5d946c - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hc48d3ec13a4b1dfe
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  64:     0x55d39b5d92d4 - tokio::runtime::task::harness::Harness<T,S>::poll::hae420076707b3d00
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  65:     0x55d39b5d1f22 - tokio::runtime::task::raw::poll::hf6b86b691a178fb9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  66:     0x55d39b5d1e2f - tokio::runtime::task::raw::RawTask::poll::h1529a45f52063cc2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  67:     0x55d39b59aa24 - tokio::runtime::task::UnownedTask<S>::run::h4ef6fd8f098da5e9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:379:9
  68:     0x55d39b5b9167 - tokio::runtime::blocking::pool::Inner::run::h04232d915462879f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:265:17
  69:     0x55d39b5b857f - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h093b0f3d470c566f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:245:17
  70:     0x55d39b5b225c - std::sys_common::backtrace::__rust_begin_short_backtrace::h43bfb8bc2d93067a
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  71:     0x55d39b5c5171 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h1e0688eb3fb8b8a4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/mod.rs:476:17
  72:     0x55d39b59cec1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb0f625c9f836a969
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:347:9
  73:     0x55d39b5ac99c - std::panicking::try::do_call::h75766e679365f1a1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  74:     0x55d39b5acf1d - __rust_try
  75:     0x55d39b5ac5e1 - std::panicking::try::h38aa1079f018e892
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  76:     0x55d39b59eb41 - std::panic::catch_unwind::h64c515da19587025
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  77:     0x55d39b5c4f80 - std::thread::Builder::spawn_unchecked::{{closure}}::h8bd1e415d1392b98
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/thread/mod.rs:475:30
  78:     0x55d39b58fb0f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h74c82b5528d22906
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  79:     0x55d39b92fcc7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  80:     0x55d39b92fcc7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  81:     0x55d39b92fcc7 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
  82:     0x7f68b048eea5 - start_thread
  83:     0x7f68afcb19fd - __clone
  84:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction


```

**Comment by djc** [comment]
This is the originating code:

```rust
            // ACK-only packets should only be sent when explicitly allowed. If we write them due
            // to any other reason, there is a bug which leads to one component announcing write
            // readiness while not writing any data. This degrades performance. The condition is
            // only checked if the full MTU is available, so that lack of space in the datagram isn't
            // the reason for just writing ACKs.
            debug_assert!(
                !(sent.is_ack_only()
                    && !can_send.acks
                    && can_send.other
                    && (buf_capacity - builder.datagram_start)
                        == self.path.max_udp_payload_size as _),
                "SendableFrames was {:?}, but only ACKs have been written",
                can_send
            );
```

So this assert (which should only trigger in debug builds) is indicating we have some bug. I'm not sure, off the top of my head, what kind of diagnostics we could enable to dig out the root cause, maybe @Ralith or @Matthias247 will?

**Comment by Ralith** [comment]
This is definitely a bug; thanks for the report! The good news is, depending on the underlying cause, it's probably not debilitating, so release builds should not be critically affected.

@Archieeeeee, is this using current master? Would you be able to record and share trace logs and/or a packet capture + key log for an instance of it occurring?

**Comment by Ralith** [comment]
One possible culprit: we determine whether we might have stream data to send as follows:
https://github.com/quinn-rs/quinn/blob/730fdaf723eef125c175fbcdba1ac3fe3324f7ce/quinn-proto/src/connection/streams/state.rs#L297-L301
However, pending streams might be discarded lazily if they were reset:
https://github.com/quinn-rs/quinn/blob/730fdaf723eef125c175fbcdba1ac3fe3324f7ce/quinn-proto/src/connection/streams/state.rs#L460-L471
This could lead to a spurious transmit attempt, producing an illegal ACK-only packet and triggering the assert.
