### ISSUE TITLE
Allow disabling backtraces in panics

### ISSUE THREAD

**Issue by casey** [quinn-rs/quinn#1927]
I'm trying to implement a custom `quinn::crypto::Session`, and I've stubbed out a lot of methods with calls to `todo!()`. When these are reached in tests, I get a backtrace in the terminal, which makes it hard to see the other output from my tests. I've confirmed that both `RUST_BACKTRACE` and `RUST_LIB_BACKTRACE` are unset, and setting them both to `0` doesn't seem to make a difference. When I unwrap `None` or `panic!()` in the test itself, I don't get a backtrace.

Is it possible to disable backtraces in panics from within quinn?

<details>
<summary>backtrace</summary>
```
     Running unittests src/main.rs (target/debug/deps/gossamer-90b343094e3ed231)

running 1 test
thread 'node::tests::bootstrap' panicked at library/core/src/panicking.rs:228:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[src/node.rs:270:5] std::env::var("RUST_BACKTRACE") = Ok(
    "0",
)
[src/node.rs:271:5] std::env::var("RUST_LIB_BACKTRACE") = Ok(
    "0",
)
thread 'node::tests::bootstrap' panicked at src/unverified_endpoint.rs:175:5:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'node::tests::bootstrap' panicked at /Users/rodarmor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-0.11.2/src/endpoint.rs:660:50:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:        0x104905a64 - std::backtrace_rs::backtrace::libunwind::trace::he4f0a5f56afe8e37
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:        0x104905a64 - std::backtrace_rs::backtrace::trace_unsynchronized::habb302958e80f800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104905a64 - std::sys_common::backtrace::_print_fmt::h9819d35e2a5cda77
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x104905a64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1049272f8 - core::fmt::rt::Argument::fmt::h626862aa6242248a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:        0x1049272f8 - core::fmt::write::heedef092c8c0962e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:        0x104902894 - std::io::Write::write_fmt::h8e9ee1c6e6a7d36d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:        0x1049058bc - std::sys_common::backtrace::_print::ha0f584bc7bfb9d2b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1049058bc - std::sys_common::backtrace::print::h417292deb95532ed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x104906ee4 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
  10:        0x104906b30 - std::panicking::default_hook::h24535936bc1f51de
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:295:9
  11:        0x1042f229c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4a11eb0407408336
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  12:        0x1042f229c - test::test_main::{{closure}}::hc692fb3a0d2a3405
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:137:21
  13:        0x1049077c4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd294eb67051ac295
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  14:        0x1049077c4 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  15:        0x1049071cc - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  16:        0x104905eec - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  17:        0x104906f3c - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  18:        0x104948b14 - core::panicking::panic_fmt::hc2b459a5bd3dce66
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  19:        0x104948f14 - core::result::unwrap_failed::h88d7eb352f20b747
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
  20:        0x10434a220 - core::result::Result<T,E>::unwrap::h363d3ede1ce88579
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
```
</details>

**Comment by djc** [comment]
I… don’t remember us doing anything special here. Are you sure this only happens from within Quinn?

**Comment by casey** [comment]
I guess I assumed that because I wasn't getting backtraces on my own panics, it was something quinn was doing. I think you're right that it might not be quinn, since it looks like a vanilla rust mutex poisoned error which is triggering the backtrace. I'm not at my computer right now, but let me debug a little and try to confirm whether or not it's quinn. Maybe if you panic in a background thread/task it always prints a backtrace.

**Comment by Ralith** [comment]
This is definitely not a quinn-specific issue. Perhaps something about panic-while-panicing? I'd try building your tests with panic=abort, maybe.
