### ISSUE TITLE
Panic in quinn-proto-0.11.9

### ISSUE THREAD

**Issue by neevek** [quinn-rs/quinn#2064]
Hi, I tried upgrading to `quinn-proto-0.11.9`, but it panicked after running for a while. 
It was bad that I lost the tmux session, and the complete stack trace was lost, I only remember that the error was something like `Panicked at 'attempt to subtract with overflow'`, it happened at `paths.rs:331`. I tried to reproduce it, but for quite a while I still can't get it panic again. I guess there might be some bugs.

**Comment by Ralith** [comment]
Unfortunately this isn't very actionable without more information. Please make arrangements to capture logs reliably in case you encounter this again.

**Comment by Ralith** [comment]
Feel free to reopen if you're able to reproduce.

**Comment by OliverNChalk** [comment]
Confirming I am encountering this same issue when debug_asserts = true. The offending line is:

https://github.com/quinn-rs/quinn/blob/8936cc059c66c6010aeee873a996f82d3fbbc389/quinn-proto/src/connection/paths.rs#L330

Trace:
```
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]: 2025-05-21T18:47:09.007252Z ERROR relayer: Application panic panic_info=PanicHookInfo { payload: Any { .. }, location: Location { file: "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/quinn-proto-0.11.11/src/connection/paths.rs", line: 330, col: 9 }, can_unwind: true, force_no_backtrace: false }
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]: thread 'quic_streamer_tpuRt' panicked at /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/quinn-proto-0.11.11/src/connection/paths.rs:330:9:
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]: attempt to subtract with overflow
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]: stack backtrace:
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    0: rust_begin_unwind
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    1: core::panicking::panic_fmt
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    2: core::panicking::panic_const::panic_const_sub_overflow
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    3: quinn_proto::connection::Connection::on_packet_acked
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    4: quinn_proto::connection::Connection::on_ack_received
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    5: quinn_proto::connection::Connection::process_payload
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    6: quinn_proto::connection::Connection::process_decrypted_packet
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    7: quinn_proto::connection::Connection::handle_packet
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    8: quinn_proto::connection::Connection::handle_event
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:    9: <quinn::connection::ConnectionDriver as core::future::future::Future>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   11: tokio::runtime::task::core::Core<T,S>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   12: tokio::runtime::task::harness::Harness<T,S>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   13: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   14: tokio::runtime::context::scoped::Scoped<T>::set
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   15: tokio::runtime::context::runtime::enter_runtime
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   16: tokio::runtime::scheduler::multi_thread::worker::run
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   17: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   18: tokio::runtime::task::core::Core<T,S>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   19: tokio::runtime::task::harness::Harness<T,S>::poll
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]:   20: tokio::runtime::blocking::pool::Inner::run
May 21 18:47:09 sfu-ams-rly-0 relayer-start[155563]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Unfortunately triggering this is unreliable and seems to be non deterministic (I'm assuming some multi thread race that results in a decrement before an increment). Maybe someone familiar with the callsites could way in how its possible for `self.bytes` to underflow? If I do somehow get a reliable reproduction I'll of course update but I'm not hopeful

**Comment by Ralith** [comment]
Can you supply complete Quinn trace logs of an instance of this happening, or at least describe in detail the type of traffic your application involves?

> I'm assuming some multi thread race that results in a decrement before an increment

This cannot happen, because all of this state is guarded by a Mutex.

**Comment by Ralith** [comment]
This has been fixed in #2319.
